[project]
name = "sx"
authors = [{ name = "Rong Vang Hoang Gia", email = "mrhuychien@gmail.com" }]
description = "Portal San Xuat RVHG - so hoa san xuat banh & bot dau xanh"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
